[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "postgresql"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm ci --only=production"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "mkdir -p backend/static",
    "cp -r frontend/dist/* backend/static/"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"